name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # 只对打了 tag 的提交触发（例如 v1.0.0）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: herfom/strapi-from-repo:${{ github.ref_name }}